version: '3.9'

services:
  # =====================
  # Custom Autoscaler App
  # =====================
  autoscaler:
    build: .
    container_name: custom-autoscaler
    restart: unless-stopped
    ports:
      - "2112:2112" # Prometheus metrics endpoint
    networks:
      - monitoring

  # =====================
  # Prometheus
  # =====================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - autoscaler
    networks:
      - monitoring

  # =====================
  # Grafana
  # =====================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
volumes:
  grafana-data:
